version: '3'
services:

  php:
    image: php:8.3-fpm
    restart: always
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - '.:/var/www/html'
      - './docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    links:
      - db
    env_file:
      - .env
    depends_on:
        -   db


  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '8081:80'
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    links:
      - php

  db:
      image: postgres:14.10
      restart: always
      environment:
          - POSTGRES_HOST=${DB_HOST}
          - POSTGRES_DB=${DB_DATABASE}
          - POSTGRES_USER=${DB_USERNAME}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
          - POSTGRES_CONNECTION=${DB_CONNECTION}
      ports:
          - "5433:5432"

  rabbitmq:
      image: rabbitmq:3.12.7-management
      hostname: rabbitmq
      restart: always
      environment:
          - RABBITMQ_DEFAULT_USER=user
          - RABBITMQ_DEFAULT_PASS=user
      ports:
          - "15672:15672"
